import type { Metadata } from "next";
import "./globals.css";
import { Cairo, Inter } from "next/font/google"
import Navbar from "@/components/custom/navbar";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className={inter.variable}>
      <body className={`${cairo.className} antialiased`}>
        <Navbar />
        {children}</body>
    </html>
  );
}
